@startuml untitled-tycoon-game
struct ProductType {
    +Name: string
    +BuyPrice: decimal
    +ShelfLife: TimeSpan
    +StackSize: uint
}
struct Product {
    +Type: ProductType
    +ExpiryDate: DateTime
}
Product -left-> ProductType

abstract class Actor {
    #Market: Market
    +Act(): void
}

class Customer {
    +ShoppingList: List<Product>
    +ShoppingCart: List<Product>
    +Mood: double
}
Customer -up-|> Actor

struct ShelfCell {
    +Height: uint
    +Products: Queue<Product>
    +ProductType: ProductType
    +Width: uint
}

class Shelf {
    -cells: List<ShelfCell>
    +Height: uint
    +Width: uint
    +HasProduct(type: ProductType): bool
    +NeedsRestocking(): bool
    +Restock(): void
    +TakeProducts(type: ProductType, count: uint): Queue<Product>
}
Shelf -up-|> Actor
Shelf -down-> ShelfCell

class Checkout {
    -currentCustomer: Customer
    +Customers: Queue<Customer>
    +Open: bool
}
Checkout -up-|> Actor

enum EmployeeTask  {
    Idle
    OperateCheckout
    OperateSelfCheckout
    Restock
}

class Employee {
    -checkout: Checkout?
    +CheckoutEfficiency: uint
    +Task: EmployeeTask
}
Employee -up-|> Actor
Employee --> EmployeeTask

class Market {
    +Actors: List<Actor>
    +Balance: decimal
    +Products: List<ProductType>
    +Rating: double
    +Storage: Dictionary<ProductType, Queue<Product>>
}
Market --> Actor
Market -left-> Product

struct GameRules {
    
}

class Level {
    +Market: Market
    +Rules: GameRules
    +Time: DateTime
}
Level -right-> GameRules
Level --> Market
@enduml