@startuml untitled-tycoon-game
struct ProductType {
    +Name: string
    +BuyPrice: decimal
    +ShelfLife: TimeSpan
    +StackSize: uint
}
struct Product {
    +Type: ProductType
    +ExpiryDate: DateTime
}
Product -left-> ProductType

abstract class Actor {
    +Act(): void
    #GetMarket(): Market
}

struct ShoppingListItem {
    +Count: uint
    +IsImportant: bool
    +Type: ProductType
}

class Customer {
    +ShoppingList: List<ShoppingListItem>
    +ShoppingCart: List<Product>
    +Mood: double
}
Customer -up-|> Actor
Customer -down-> ShoppingListItem

struct ShelfCell {
    +Height: uint
    +Products: Queue<Product>
    +ProductType: ProductType
    +Width: uint
}

class Shelf {
    +Cells: List<ShelfCell>
    +Height: uint
    +Width: uint
    +HasProduct(type: ProductType): bool
    +NeedsRestocking(): bool
    +Restock(): void
    +TakeProducts(type: ProductType, count: uint): Queue<Product>
}
Shelf -up-|> Actor
Shelf -down-> ShelfCell

class Checkout {
    +CurrentCustomer: Customer
    +Customers: Queue<Customer>
    +Open: bool
}
Checkout -up-|> Actor

enum EmployeeTask  {
    Idle
    OperateCheckout
    OperateSelfCheckout
    Restock
}

class Employee {
    +Checkout: Checkout?
    +CheckoutEfficiency: uint
    +Task: EmployeeTask
}
Employee -up-|> Actor
Employee --> EmployeeTask

class Market {
    +Actors: List<Actor>
    +Name: string
    +Products: List<ProductType>
    +Storage: Dictionary<ProductType, Queue<Product>>
    
    +Tick(): void
}
Market --> Actor
Market -left-> Product

struct Savefile {
    +Balance: decimal
    +Created
    +FoodExpires: bool
    +GameTime: DateTime
    +Name: string
    +Rating: double
}
Savefile -down-> Market

class Game {
    +ActiveSavefile: static Savefile?
    +GetSavefileInfos(): static List<Savefile>
    +Load(name: string): void
    +Save(): void
}
Game -down-> Savefile
@enduml